name: IaC Security Scan (Terraform + Checkov)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform -chdir=. init

      - name: Terraform Validate
        run: terraform -chdir=. validate

      - name: Terraform Plan
        run: terraform -chdir=. plan -input=false || true

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov Scan
        run: checkov -d . -o cli || true
